### ISSUE TITLE
Failed to send_join via any server when joining #rust:matrix.org.

### ISSUE THREAD

**Issue by cyphar** [matrix-org/synapse#7033]
### Description

I've been running my own homeserver for over a year now, and it works great. But I just tried to join `#rust:matrix.org` and synapse fails to join with the following error shown on the client:

```
Failed to send_join via any server
```

The full backtrace for one of these events [is attached](https://github.com/matrix-org/synapse/files/4287289/homeserver.log.txt). Looks like the core issue is this `AttributeError`:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/synapse/federation/federation_client.py", line 402, in _try_destination_list
    res = await callback(destination)
  File "/usr/lib/python3.7/site-packages/synapse/federation/federation_client.py", line 589, in send_request
    valid_pdus_map = {p.event_id: p for p in valid_pdus}
  File "/usr/lib/python3.7/site-packages/synapse/federation/federation_client.py", line 589, in <dictcomp>
    valid_pdus_map = {p.event_id: p for p in valid_pdus}
AttributeError: 'coroutine' object has no attribute 'event_id'
```

### Steps to reproduce

- Run matrix-synapse 1.11.0.
- Try to join `#rust:matrix.org`.
- Note the behaviour listed above.

### Version information
- **Homeserver**: `cyphar.com`
- **Version**: `1.11.0`.
- **Install method**: Package manager.
- **Platform**: openSUSE Tumbleweed, inside an LXD container on openSUSE Leap 15.1.

**Comment by clokep** [comment]
Thanks for the report! This looks like it is a duplicate of #6978, which was fixed in Synapse 1.11.1. Please re-open this issue if it is still happening after upgrading Synapse to 1.11.1.

**Comment by cyphar** [comment]
Ah, thanks. Yeah working on updating the package in openSUSE at the moment. :heart:

**Comment by sl5net** [comment]
i have the problem problem from window to linux mint. in the LAN. 
"Failed to make_join via any server"

**Comment by sl5net** [comment]
please set "Closed" too "open"

**Comment by cyphar** [comment]
@sl5net matrix.netzgemeinde.eu should update to synapse 1.11.1 or later (1.17.0 was released some time ago).

**Comment by cyphar** [comment]
That's odd, it seems like your homeserver is actually running `1.17.0` where the issue should've been fixed:

```
% curl https://matrix.netzgemeinde.eu/_matrix/federation/v1/version 
{
    "server": {
        "name": "Synapse",
        "version": "1.17.0"
    }
}
```

**Comment by mnowiasz** [comment]
Tried to join #rust myself, got the following error in homeserver.log:

```
2020-07-20 07:56:53,478 - synapse.http.server - 79 - ERROR - GET-2503855 - Failed handle request via 'ClientDirectoryServer': <XForwardedForRequest at 0x7f43a75d5370 method='GET' uri='/_matrix/client/r0/directory/room/%23rust%3Amatrix.org' clientproto='HTTP/1.1' site=8008>
Traceback (most recent call last):
  File "/home/matrix/synapse/env/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 436, in _send_request
    response = yield request_deferred
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.defer.CancelledError: >]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matrix/synapse/env/lib/python3.8/site-packages/synapse/http/server.py", line 228, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/home/matrix/synapse/env/lib/python3.8/site-packages/synapse/http/server.py", line 399, in _async_render
    callback_return = await raw_callback_return
  File "/home/matrix/synapse/env/lib/python3.8/site-packages/synapse/rest/client/v1/directory.py", line 52, in on_GET
    res = await dir_handler.get_association(room_alias)
  File "/home/matrix/synapse/env/lib/python3.8/site-packages/synapse/handlers/directory.py", line 236, in get_association
    result = await self.federation.make_query(
  File "/home/matrix/synapse/env/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/synapse/env/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/synapse/env/lib/python3.8/site-packages/synapse/federation/transport/client.py", line 176, in make_query
    content = yield self.client.get_json(
  File "/home/matrix/synapse/env/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/synapse/env/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/synapse/env/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 794, in get_json
    response = yield self._send_request_with_optional_trailing_slash(
  File "/home/matrix/synapse/env/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/synapse/env/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/synapse/env/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 252, in _send_request_with_optional_trailing_slash
    response = yield self._send_request(request, **send_request_args)
  File "/home/matrix/synapse/env/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/synapse/env/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/synapse/env/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 443, in _send_request
    raise RequestSendFailed(e, can_retry=True) from e
synapse.api.errors.RequestSendFailed: Failed to send request: ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.defer.CancelledError: >]````

**Comment by clokep** [comment]
That seems to be unrelated to this issue (the stack trace is different). My initial guess would be that the server was not responding / was slow to respond.

**Comment by Half-Shot** [comment]
`#rust:matrix.org` contains ~6800 members. This is likely caused by https://github.com/matrix-org/synapse/issues/1211.

**Comment by TheGreatestJannet** [comment]
Is there a fix for this? I can't join `#nextcloud:matrix.org` at all.
I also get the following error:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
    result = current_context.run(gen.send, result)
StopIteration: {'ed25519:auto': FetchKeyResult(verify_key=<nacl.signing.VerifyKey object at 0x7f1dc06d7d90>, valid_until_ts=1576767829750), 'ed25519:a_RXGa': FetchKeyResult(verify_key=<nacl.signing.VerifyKey object at 0x7f1dc45c2100>, valid_until_ts=1636323490080)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 576, in _try_destination_list
    return await callback(destination)
  File "/usr/local/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 825, in send_request
    await concurrently_execute(
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "/usr/local/lib/python3.8/site-packages/synapse/util/async_helpers.py", line 192, in _concurrently_execute_inner
    await maybe_awaitable(func(value))
  File "/usr/local/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 815, in _execute
    valid_pdu = await self._check_sigs_and_hash_and_fetch_one(
  File "/usr/local/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 458, in _check_sigs_and_hash_and_fetch_one
    res = await self._check_sigs_and_hash(room_version, pdu)
  File "/usr/local/lib/python3.8/site-packages/synapse/federation/federation_base.py", line 70, in _check_sigs_and_hash
    if not check_event_content_hash(pdu):
  File "/usr/local/lib/python3.8/site-packages/synapse/crypto/event_signing.py", line 42, in check_event_content_hash
    name, expected_hash = compute_content_hash(event.get_pdu_json(), hash_algorithm)
  File "/usr/local/lib/python3.8/site-packages/synapse/crypto/event_signing.py", line 96, in compute_content_hash
    event_json_bytes = encode_canonical_json(event_dict)
  File "/usr/local/lib/python3.8/site-packages/canonicaljson.py", line 83, in encode_canonical_json
    s = _canonical_encoder.encode(json_object)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/site-packages/canonicaljson.py", line 36, in _default
    raise TypeError(
TypeError: Object of type Decimal is not JSON serializable
```
