### ISSUE TITLE
Cannot set a user as an admin with the admin API

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#6910]
```
2020-02-13 19:15:53,449 - synapse.http.server - 110 - ERROR - PUT-31 - Failed handle request via 'UserRestServletV2': <SynapseRequest at 0x7f6a6035bfd0 method='PUT' uri='/_synapse/admin/v2/users/@mjolnir-dev:redacted' clientproto='HTTP/1.0' site=8008>
Traceback (most recent call last):
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: {'displayname': 'mjolnir-dev', 'avatar_url': None}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: {'displayname': 'mjolnir-dev', 'avatar_url': None}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: ProfileInfo(avatar_url=None, display_name='mjolnir-dev')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/http/server.py", line 78, in wrapped_request_handler
    await h(self, request)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/http/server.py", line 331, in _async_render
    callback_return = await callback_return
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/rest/admin/users.py", line 185, in on_PUT
    await self.admin_handler.set_user_server_admin(
AttributeError: 'AdminHandler' object has no attribute 'set_user_server_admin'

```

Synapse 1.10

Request:
```
curl -s -X PUT -H "Authorization: Bearer ${token}" -H "Content-Type: application/json" -d '{"admin":true}' https://dev.t2host.io/_synapse/admin/v2/users/@mjolnir-dev:redacted
{
    "errcode": "M_UNKNOWN",
    "error": "Internal server error"
}
```

**Comment by richvdh** [comment]
I think this was introduced by #6751

**Comment by dklimpel** [comment]
Also old api (/_synapse/admin/v1/users/<user_id>/admin) is broken

**Comment by Cadair** [comment]
This has just bit me as well, I had no idea why it was misbehaving until @Half-Shot pointed me at this.

**Comment by richvdh** [comment]
@dklimpel has made a PR to fix this at #6928; hopefully it will land soon.
