### ISSUE TITLE
Internal server error on HTTP HEAD requests for media repository

### ISSUE THREAD

**Issue by michaelkaye** [matrix-org/synapse#6746]
This error was introduced somewhere in https://github.com/matrix-org/synapse/compare/ce72a9ccdb0c4e5a409d85ddccb6c9570048ebc7...a099ab7d380d3bf3b566d93454ecce80e29b661f

And I think https://github.com/matrix-org/synapse/pull/6686 might be related

```
2020-01-20 06:25:28,773 - twisted - 192 - CRITICAL -  - 
Capture point (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/synapse/src/synapse/app/media_repository.py", line 175, in <module>
    start(sys.argv[1:])
  File "/home/synapse/src/synapse/app/media_repository.py", line 170, in start
    _base.start_worker_reactor("synapse-media-repository", config)
  File "/home/synapse/src/synapse/app/_base.py", line 77, in start_worker_reactor
    run_command=run_command,
  File "/home/synapse/src/synapse/app/_base.py", line 137, in start_reactor
    daemon.start()
  File "/home/synapse/env-py37/lib/python3.7/site-packages/daemonize.py", line 248, in start
    self.action(*privileged_action_result)
  File "/home/synapse/src/synapse/app/_base.py", line 114, in run
    run_command()
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/base.py", line 1272, in run
    self.mainLoop()
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/base.py", line 1284, in mainLoop
    self.doIteration(t)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/epollreactor.py", line 235, in doPoll
    log.callWithLogger(selectable, _drdw, selectable, fd, event)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/web/http.py", line 2924, in dataReceived
    return self._channel.dataReceived(data)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/web/http.py", line 2217, in dataReceived
    return basic.LineReceiver.dataReceived(self, data)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/protocols/basic.py", line 572, in dataReceived
    why = self.lineReceived(line)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/web/http.py", line 2105, in lineReceived
    self.allContentReceived()
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/web/http.py", line 2196, in allContentReceived
    req.requestReceived(command, path, version)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/web/http.py", line 920, in requestReceived
    self.process()
Traceback (most recent call last):
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/web/server.py", line 199, in process
    self.render(resrc)
  File "/home/synapse/src/synapse/http/site.py", line 132, in render
    Request.render(self, resrc)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/web/server.py", line 259, in render
    body = resrc.render(self)
  File "/home/synapse/src/synapse/http/server.py", line 389, in render
    return super().render(request)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/web/resource.py", line 260, in render_HEAD
    return self.render_GET(request)
AttributeError: 'DownloadResource' object has no attribute 'render_GET'
```

**Comment by richvdh** [comment]
This doesn't appear to be a new issue: I think it was introduced by #5475

**Comment by richvdh** [comment]
related: #6746

**Comment by richvdh** [comment]
A 500 also happens for HEAD requests for `/_matrix/saml2/authn_response` for servers that have SAML auth enabled (which is unsurprising, given that uses the same `DirectServeResource` as the media endpoints).

**Comment by richvdh** [comment]
for clarity: the problem here is that `DirectServeResource` implements GET requests by overriding `render` and passing GET requests to `_async_render_GET`. Non-GET requests are passed onto the parent implementation, which calls the default `render_HEAD`, which tries to call the non-existent `render_GET`.

**Comment by clokep** [comment]
> Non-GET requests are passed onto the parent implementation, which calls the default `render_HEAD`, which tries to call the non-existent `render_GET`.

This bit doesn't seem to be true anymore (as of #7732).

I suspect this is actually already fixed, but should definitely be fixed with #7999.
