### ISSUE TITLE
Synchrotrons and federation sender broken on latest develop

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#2655]
### Description

They spit out errors like:

```
synchrotron_1 - 2017-11-09 05:47:09,028 - synapse.http.server - 139 - ERROR - GET-908- Failed handle request synapse.http.server._async_render on <synapse.http.server.JsonResource object at 0x7ff0b7509810>: <XForwardedForRequest at 0x7ff0b446b710 method=GET uri=/_matrix/client/r0/sync?filter=120&full_state=false&timeout=10000&since=paginationTokenHere&access_token=<redacted> clientproto=HTTP/1.0 site=8050>
Traceback (most recent call last):
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/http/server.py", line 116, in wrapped_request_handler
    yield request_handler(self, request, request_metrics)
AttributeError: 'SynchrotronSlavedStore' object has no attribute '_state_group_cache'
synchrotron_1 - 2017-11-09 05:47:09,029 - synapse.access.http.8050 - 91 - INFO - GET-908- 138.197.141.99 - 8050 - {@voyager:t2bot.io} Processed request: 85ms (27ms, 4ms) (163ms/89) 55B 500 "GET /_matrix/client/r0/sync?filter=120&full_state=false&timeout=10000&since=paginationTokenHere&access_token=<redacted> HTTP/1.0" "None"
```

```
federation_sender - 2017-11-09 05:49:53,937 - synapse.replication.tcp.client - 106 - INFO - - Received rdata events -> 43860735
federation_sender - 2017-11-09 05:49:53,941 - twisted - 131 - CRITICAL - - Unhandled error in Deferred:
federation_sender - 2017-11-09 05:49:53,942 - twisted - 131 - CRITICAL - -
Traceback (most recent call last):
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/storage/state.py", line 714, in _get_state_for_groups
    group
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/storage/state.py", line 687, in _get_all_state_from_cache
    is_all, _, state_dict_ids = self._state_group_cache.get(group)
AttributeError: 'FederationSenderSlaveStore' object has no attribute '_state_group_cache'
```

### Version information

- **Homeserver**: t2bot.io
- **Version**:        0.24.1 (develop) 
- **Install method**: pip
- **Platform**:       container

**Comment by turt2live** [comment]
Because it was an issue last time, here's the nginx config I have for the synchrotron:
```
location /_matrix/client/r0/sync {
    include /etc/nginx/mx_proxy_settings.conf;
    proxy_pass http://synchrotron;
}
```
(I only use the /sync endpoint, so the others don't get proxied).

`mx_proxy_settings` is just
```
proxy_read_timeout 600s;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $remote_addr;
```

**Comment by turt2live** [comment]
This appears to have been broken by https://github.com/matrix-org/synapse/commit/f5cf3638e9c6086e1c33ddad8eda9298cf53a58e which was https://github.com/matrix-org/synapse/pull/2649

**Comment by richvdh** [comment]
This got fixed by ab335ed.
