### PR TITLE
Fix error reporting when using `opentracing.trace`

### PR DESCRIPTION
**Pull request by erikjohnston**
In particular `start_active_span` returns a scope, which is meant to be a context manager that returns itself, but it didn't. This fixes that.

We also clean some other stuff up, we don't actually need to set `error=True` tag manually, that happens for us, and there is no point having the if opentracing guard there given we both have it up a layer and `start_active_span` returns a null context manager anyway.

Broke in #7872 

Stack trace:

```
AttributeError: 'NoneType' object has no attribute 'span'
  File "synapse/http/server.py", line 228, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "synapse/http/server.py", line 399, in _async_render
    callback_return = await raw_callback_return
  File "synapse/rest/client/v2_alpha/room_keys.py", line 134, in on_PUT
    ret = await self.e2e_room_keys_handler.upload_room_keys(user_id, version, body)
  File "synapse/logging/opentracing.py", line 747, in _trace_inner
    scope.span.set_tag(tags.ERROR, True)
```

### CODE REVIEW

File: changelog.d/7961.bugfix [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix sometimes returning 500 instead of the actual error response when using opentracing.
```
Comment (richvdh) [inline changelog.d/7961.bugfix]:
```suggestion
Fix a bug which could cause `500 Internal Server Error` to be returned instead of the actual response when an error was returned from REST APIs and opentracing was enabled..
```

File: changelog.d/7961.bugfix [hunk 2]
```diff
@@ -0,0 +1 @@
+Fix a long standing bug where the tracing of async functions with opentracing was broken.
```
Comment (richvdh) [inline changelog.d/7961.bugfix:1]: oh this is fine too

File: synapse/logging/opentracing.py [hunk 3]
```diff
@@ -737,24 +737,14 @@ def decorator(func):
 
             @wraps(func)
             async def _trace_inner(*args, **kwargs):
-                if opentracing is None:
+                with start_active_span(_opname):
                     return await func(*args, **kwargs)
```
Comment (clokep) [inline synapse/logging/opentracing.py:741]: I tried to remove this earlier and it caused issues: https://github.com/matrix-org/synapse/pull/7872/#discussion_r455893714

I think the case this protects against is having `opentracing` installed, but disabled via the config.

Comment (erikjohnston) [reply synapse/logging/opentracing.py:741]: Did you also remove the explicit `scope.span.set_tag(...)`?

Comment (clokep) [reply synapse/logging/opentracing.py:741]: Ah, no. That makes sense. 👍
