### PR TITLE
Move get_time_of_last_push_action_before to the EventPushActionsWorkerStore

### LINKED ISSUE #7054: AttributeError: 'GenericWorkerSlavedStore' object has no attribute 'get_time_of_last_push_action_before'
Happens when sending out new email notifications. Given it happened on `matrix-org-hotfixes` between Feb 19th and Feb 27th, I assume this was caused by https://github.com/matrix-org/synapse/pull/6964.

### PR DESCRIPTION
**Pull request by babolivier**
Fixes #7054

I also had a look at the rest of the functions in
`EventPushActionsStore` and in the push notifications send code and it
looks to me like there shouldn't be any other method with this issue in
this part of the codebase.

### CODE REVIEW

**Comment by clokep** [comment]
Also @babolivier gave me a good explanation on Matrix which is worth including here:

> Also, the reason the other commit fixes things is because in worker mode we don't give workers the full store, we give them a slaved store which inherits from multiple worker stores, while the master process has a datastore which inherits from all of the worker stores and the non-worker stores.
> 
> In this case, the pusher worker is given the `GenericWorkerSlavedStore`, which inherits (parly) from the `SlavedEventStore`, which inherits (partly) from the `EventPushActionsWorkerStore`; and on the other hand, the master process gets the `DataStore`, which inherits (partly) from the `EventPushActionsStore`, which itself inherits from the `EventPushActionsWorkerStore`.
> 
> What the `AttributeError` is complaining about, is that the function `get_time_of_last_push_action_before` was not defined for the `GenericWorkerSlavedStore`, which means that the root cause is that it was defined in the `EventPushActionsStore` but not in the `EventPushActionsWorkerStore`.
