### ISSUE TITLE
synapse 1.82 fails to start

### ISSUE THREAD

**Issue by hagenbauer** [matrix-org/synapse#15513]
### Description

After some upgrades synapse server fails to start 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.9/site-packages/synapse/__init__.py", line 24, in <module>
    from synapse.util.rust import check_rust_lib_up_to_date
  File "/usr/local/lib/python3.9/site-packages/synapse/util/__init__.py", line 31, in <module>
    from synapse.logging import context
  File "/usr/local/lib/python3.9/site-packages/synapse/logging/__init__.py", line 17, in <module>
    from synapse.logging._remote import RemoteHandler
  File "/usr/local/lib/python3.9/site-packages/synapse/logging/_remote.py", line 29, in <module>
    from twisted.internet.endpoints import (
  File "/usr/local/lib/python3.9/site-packages/twisted/internet/endpoints.py", line 67, in <module>
    from OpenSSL.SSL import Error as SSLError
  File "/usr/local/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/usr/local/lib/python3.9/site-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/usr/local/lib/python3.9/site-packages/OpenSSL/crypto.py", line 3258, in <module>
    utils.deprecated(
TypeError: deprecated() got an unexpected keyword argument 'name'

```

### Steps to reproduce

synapse server running in a FreeBSD jail happily for month. It seems that some upgrades have created this situation. Unfortunately I am unable to tell the exact steps

### Homeserver

caserio.de

### Synapse Version

1.82

### Installation Method

pip (from PyPI)

### Database

postresql same server

### Workers

Single process

### Platform

FreeBSD 13.1

### Configuration

Single Server according to documentation 

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.9/site-packages/synapse/__init__.py", line 24, in <module>
    from synapse.util.rust import check_rust_lib_up_to_date
  File "/usr/local/lib/python3.9/site-packages/synapse/util/__init__.py", line 31, in <module>
    from synapse.logging import context
  File "/usr/local/lib/python3.9/site-packages/synapse/logging/__init__.py", line 17, in <module>
    from synapse.logging._remote import RemoteHandler
  File "/usr/local/lib/python3.9/site-packages/synapse/logging/_remote.py", line 29, in <module>
    from twisted.internet.endpoints import (
  File "/usr/local/lib/python3.9/site-packages/twisted/internet/endpoints.py", line 67, in <module>
    from OpenSSL.SSL import Error as SSLError
  File "/usr/local/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/usr/local/lib/python3.9/site-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/usr/local/lib/python3.9/site-packages/OpenSSL/crypto.py", line 3258, in <module>
    utils.deprecated(
TypeError: deprecated() got an unexpected keyword argument 'name'
```

**Comment by Cyrix126** [comment]
Same issue after the upgrade from 1.81 to 1.82 on Debian arm64

**Comment by Cyrix126** [comment]
```
2023-05-01 12:39:31,359 - synapse.app._base - 212 - ERROR - main - Exception during startup
Traceback (most recent call last):
  File "/home/rockserver/synapse/env/lib/python3.9/site-packages/synapse/app/homeserver.py", line 352, in setup
    hs.setup()
  File "/home/rockserver/synapse/env/lib/python3.9/site-packages/synapse/server.py", line 329, in setup
    self.datastores = Databases(self.DATASTORE_CLASS, self)
  File "/home/rockserver/synapse/env/lib/python3.9/site-packages/synapse/storage/databases/__init__.py", line 65, in __init__
    with make_conn(database_config, engine, "startup") as db_conn:
  File "/home/rockserver/synapse/env/lib/python3.9/site-packages/synapse/storage/database.py", line 161, in make_conn
    native_db_conn = engine.module.connect(**db_params)
  File "/home/rockserver/synapse/env/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 5432?
```

More problematic is that a downgrade to 1.81 doesn't solve the issue.

**Comment by hagenbauer** [comment]
It seems to be cause by some pip dependency hell. Not sure what really solved it but after 

`
pip install --upgrade pip
pip install --upgrade pyopenssl
pip install --upgrade matrix-synapse

`
its working now. In between I saw some errors regarding matrix-common which was updated in the last step. 

Now matrix-synapse is starting
