### PR TITLE
Fix regression caused by #13573

### PR DESCRIPTION
**Pull request by erikjohnston**
Broke in #13573. See https://github.com/matrix-org/synapse/pull/13573#discussion_r952560620

Example stacktrace:

```
Traceback (most recent call last):
  File "/home/erikj/synapse/synapse/federation/sender/__init__.py", line 453, in handle_event
    destinations = await self.state.get_hosts_in_room_at_events(
  File "/home/erikj/synapse/synapse/state/__init__.py", line 251, in get_hosts_in_room_at_events
    return await self.store.get_joined_hosts(room_id, state, entry)
  File "/home/erikj/synapse/synapse/storage/databases/main/roommember.py", line 1064, in get_joined_hosts
    return await self._get_joined_hosts(
  File "/home/erikj/.synapse39/lib/python3.9/site-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "/home/erikj/synapse/synapse/storage/databases/main/roommember.py", line 1134, in _get_joined_hosts
    host = intern_string(get_domain_from_id(user_id))
  File "/home/erikj/synapse/synapse/types.py", line 211, in get_domain_from_id
    idx = string.find(":")
AttributeError: 'NoneType' object has no attribute 'find'
```

### CODE REVIEW

**Review by Fizzadar — APPROVED** [review]
Thank you for fixing my mess @erikjohnston ❤️!

**Review by reivilibre — APPROVED** [review]
lucky spot :)
