### ISSUE TITLE
Failed to upload Images running pyllow 10.0

### ISSUE THREAD

**Issue by DavidMarec** [matrix-org/synapse#15915]
### Description

The 10.0.0 release [Py-Pyllow](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html)  removed some constants like `Image.ANTIALIAS`. 

This leads to failure when users request image uploading:
```
 File "/usr/local/lib/python3.9/site-packages/synapse/media/thumbnailer.py", line 134, in _resize
    return self.image.resize((width, height), Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

Any clue to solve this ?

### Steps to reproduce

Upgrade py-pyllow to  `10.0.0`

### Homeserver

kreuz.lapinbilly.eu

### Synapse Version

1.85.2

### Installation Method

Other (please mention below)

### Database

single

### Workers

Single process

### Platform

FreeBSD 13.2, installed from ports.

### Relevant log output

```shell
2023-07-11 07:30:57,854 - synapse.media.media_repository - 204 - INFO - POST-58622 - Stored local media in file '/usr/local/etc/matrix-synapse/media_store/local_content/VI/AB/IdXGZfZtJPthfWxsrSjc'
2023-07-11 07:30:57,910 - synapse.http.server - 130 - ERROR - POST-58622 - Failed handle request via 'UploadResource': <XForwardedForRequest at 0x933d287f0 method='POST' uri='/_matrix/media/r0/upload' clientproto='HTTP/1.1' site='8008'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/synapse/http/server.py", line 313, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/usr/local/lib/python3.9/site-packages/synapse/http/server.py", line 343, in _async_render
    callback_return = await raw_callback_return
  File "/usr/local/lib/python3.9/site-packages/synapse/rest/media/upload_resource.py", line 96, in _async_render_POST
    content_uri = await self.media_repo.create_content(
  File "/usr/local/lib/python3.9/site-packages/synapse/media/media_repository.py", line 215, in create_content
    await self._generate_thumbnails(None, media_id, media_id, media_type)
  File "/usr/local/lib/python3.9/site-packages/synapse/media/media_repository.py", line 797, in _generate_thumbnails
    t_byte_source = await defer_to_thread(
  File "/usr/local/lib/python3.9/site-packages/twisted/python/threadpool.py", line 244, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.9/site-packages/twisted/python/threadpool.py", line 260, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.9/site-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.9/site-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
  File "/usr/local/lib/python3.9/site-packages/synapse/logging/context.py", line 969, in g
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/synapse/media/thumbnailer.py", line 172, in crop
    with self._resize(scaled_width, scaled_height) as scaled_image:
  File "/usr/local/lib/python3.9/site-packages/synapse/media/thumbnailer.py", line 134, in _resize
    return self.image.resize((width, height), Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

**Comment by dillfrescott** [comment]
A temporary solution until the update rolls out is to downgrade Pillow and then after the update re-upgrade it back to 10

**Comment by clokep** [comment]
Duplicates #15873.
