### PR TITLE
Fix losing incoming EDUs if debug logging enabled

### LINKED ISSUE #11889: Federation dying with `AttributeError: 'dict' object has no attribute 'edu_type'` or `... no attribute 'content'`
### Description

After upgrading my homeserver to 1.51.0 yesterday, I noticed people on other homeservers weren't responding to my messages. On the receiving side some messages were getting through to me, but not all of them.

Digging into the logs, I noticed my Synapse wasn't able to process some transactions, failing with errors like:

```
2022-02-02 13:01:41,267 - synapse.federation.transport.server.federation:91 | INFO - PUT-82644 - Received txn 1643718649381 from matrix.org. (PDUs: 50, EDUs: 98)
2022-02-02 13:01:41,267 - synapse.federation.transport.server.federation:114 | ERROR - PUT-82644 - 'dict' object has no attribute 'edu_type'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
    result = current_context.run(gen.send, result)
StopIteration: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
    result = current_context.run(gen.send, result)
StopIteration: {'ed25519:a_RXGa': FetchKeyResult(verify_key=<nacl.signing.VerifyKey object at 0x814e38370>, valid_until_ts=1643844371003)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/synapse/federation/transport/server/federation.py", line 101, in on_PUT
    device_list_updates = [
  File "/usr/local/lib/python3.8/site-packages/synapse/federation/transport/server/federation.py", line 104, in <listcomp>
    if edu.edu_type in DEVICE_UPDATE_EDUS
AttributeError: 'dict' object has no attribute 'edu_type'
```

The offending line seems to have been introduced in #11760. I'm not sure why that logger was automatically enabled for me (should it have been?), but as a workaround I reduced `DEBUG` to `WARN` and things started working again.

### Version information

- **Homeserver**: termina.org.uk
- **Version**: 1.51.0
- **Install method**: package manager
- **Platform**: FreeBSD 12

### PR DESCRIPTION
**Pull request by DMRobertson**
Missed in #11760.

Fixes #11889. Homeservers should only be affected if the
`synapse.8631_debug` logger was enabled for DEBUG mode.

I am not sure if this merits a bugfix release: I think the logging can
be disabled in config if anyone is affected? But it is still pretty bad.

### CODE REVIEW

File: synapse/federation/transport/server/federation.py [hunk 1]
```diff
@@ -113,7 +113,7 @@ async def on_PUT(
                 device_list_updates = [
                     edu.content
                     for edu in transaction_data.get("edus", [])
-                    if edu.edu_type in DEVICE_UPDATE_EDUS
+                    if edu.get("edu_type") in DEVICE_UPDATE_EDUS
```
Comment (clokep) [inline synapse/federation/transport/server/federation.py:116]: This could still error if the `edu_type` is weird (e.g. a list). A way around this is making `DEVICE_UPDATE_EDUS` into a `list`, not a `set`.

Comment (DMRobertson) [reply synapse/federation/transport/server/federation.py:116]: Oh I see, I'm implicitly assuming that the edu_type is hashable.

Comment (clokep) [reply synapse/federation/transport/server/federation.py:116]: Yep! It is *probably* OK, but if the downside is breaking federation...that's pretty bad.

Comment (DMRobertson) [reply synapse/federation/transport/server/federation.py:116]: That's done. I haven't fixed up the TX side here

https://github.com/matrix-org/synapse/blob/f160fe18e3cc5604375f491300d12dd5c7e9b9b2/synapse/federation/sender/transaction_manager.py#L128-L138

because there we really do have an `Edu` struct, and its type is something we should be fully in control of.

**Review by clokep — APPROVED** [review]

File: synapse/federation/transport/server/federation.py [hunk 2]
```diff
@@ -109,11 +109,11 @@ async def on_PUT(
             )
 
             if issue_8631_logger.isEnabledFor(logging.DEBUG):
-                DEVICE_UPDATE_EDUS = {"m.device_list_update", "m.signing_key_update"}
+                DEVICE_UPDATE_EDUS = ["m.device_list_update", "m.signing_key_update"]
                 device_list_updates = [
                     edu.content
```
Comment (DMRobertson) [inline synapse/federation/transport/server/federation.py:114]: `edu.content` does not exist.
