### ISSUE TITLE
Error 500 on login (LDAP) after upgrade to 0.18.4

### ISSUE THREAD

**Issue by rafaelmr2** [matrix-org/synapse#1643]
After upgrade we can login anymore. Log below:

```
2016-11-23 12:36:02,100 - synapse.http.server - 139 - ERROR - POST-209- Failed handle request synapse.http.server._async_render on <synapse.rest.ClientRestResource object at 0x4b23550>: <SynapseRequest at 0x54cb8c0 method=POST uri=/_matrix/client/r0/login? clientproto=HTTP/1.1 site=8448>
Traceback (most recent call last):
  File "/root/.synapse/lib/python2.7/site-packages/synapse/http/server.py", line 116, in wrapped_request_handler
    yield request_handler(self, request, request_metrics)
AttributeError: 'module' object has no attribute 'AUTH_SIMPLE'
```

Thanks

**Comment by oerdnj** [comment]
From ldap3 2.0.7 changelog:
```
2.0.7 2016.10.27

        FIRST RELEASE OF LDAP3 V2
[...]
        The following older constants in ldap3 have been removed, please use the suggested ones:
        AUTH_ANONYMOUS = ANONYMOUS
        AUTH_SIMPLE = SIMPLE
[...]
```

It can be fixed for the moment by forcing a downgrade to 1.x version:
`pip install ldap3==1.4.0`

**Comment by rafaelmr2** [comment]
Worked. Thanks.

**Comment by oerdnj** [comment]
This is just a workaround and needs to be properly fixed in the release. So please reopen the bug.

**Comment by rafaelmr2** [comment]
Sorry. Reopened.

**Comment by erikjohnston** [comment]
This should be fixed in the next release, v0.18.5, ftr

**Comment by mweinelt** [comment]
This was addresed in https://github.com/matrix-org/matrix-synapse-ldap3/commit/f7460ece6b3552810f82d7d1080067080c113c92.
