### PR TITLE
Remove unused federation endpoint (`query_auth`)

### LINKED ISSUE #6997: Kill broken and unused `FederationServer.on_query_auth_request`
We talked a bit about `FederationBase` calling a `FederationClient` method on Matrix, wanted to capture the results from rich:
> I'm pretty sure I decided that `FederationServer.on_query_auth_request` had been broken forever and needed to die, which means that `_check_sigs_and_hash_and_fetch` can move to `FederationClient`
> some more context: `_on_query_auth_request` implements an undocumented, unused REST endpoint

_Originally posted by @clokep in https://github.com/matrix-org/synapse/pull/6996#issuecomment-591509354_

### PR DESCRIPTION
**Pull request by clokep**
This removes the unused federation endpoint at `/_matrix/federation/v1/query_auth/{roomId}/{eventId}`.

As part of this it also:
* Moves `_check_sigs_and_hash_and_fetch` from `FederationBase` to `FederationClient` (since it calls into `FederationClient.get_pdu`).
* Converts `_check_sigs_and_hash_and_fetch` to be async/await.
* Fixes type issues that `mypy` found.

~~I need to put up an MSC for this work still, but I wanted to see it run through CI.~~ See [MSC2451](https://github.com/matrix-org/matrix-doc/pull/2451).

Fixes #6997

### CODE REVIEW

File: synapse/federation/federation_client.py [hunk 1]
```diff
@@ -345,6 +346,83 @@ def claim_client_keys(self, destination, content, timeout):
...
+                    pdu.event_id, allow_rejected=True, allow_none=True
+                )
+
+            if not res and pdu.origin != origin:
+                try:
+                    res = yield defer.ensureDeferred(
+                        self.get_pdu(
+                            destinations=[pdu.origin],
+                            event_id=pdu.event_id,
+                            room_version=room_version,  # type: ignore
```
Comment (clokep) [inline synapse/federation/federation_client.py]: Without ignoring this for mypy it complains:

```
synapse/federation/federation_client.py:399: error: Argument "room_version" to "get_pdu" of "FederationClient" has incompatible type "str"; expected "RoomVersion"  [arg-type]
```

I attempted to fix this in e5e5b4c7846650cb6c19f4e563e3c4312973b53c, but that seems to break SyTest. I'm not 100% confident whether mypy is in error or the code is, although I did trace through it and it seems like the code is wrong. 🤷‍♂

Comment (clokep) [reply synapse/federation/federation_client.py]: (Or maybe the typing is wrong on one of these functions.)

**Comment by clokep** [comment]
I believe this is ready for review, minus any additional spec work.

File: synapse/federation/federation_client.py (hunk 1 above)
Comment (richvdh) [reply synapse/federation/federation_client.py]: uh yeah, mypy has a point: this doesn't look right.

It's a bit of an edge-case so I can believe it's been broken for a few weeks without us noticing. Looks like it got broken in f84700fba8cd9345d7a1a025462c7f8650f27386, for the same reason that 0cb0c7bcd529b0dda92aff0dae6277dfcb6f6e29: I didn't find this use of `get_pdu` when searching.

To fix it, it looks like it should be easy enough to pass a `RoomVersion` object into `_check_sigs_and_hash_and_fetch` instead of a str? Don't know if you want to do that in this PR or another.

Comment (clokep) [reply synapse/federation/federation_client.py]: I'd like to do it in a follow-up if that's OK. I *think* this is what my commit above does and it ends up being a bit more invasive than expected.

Comment (clokep) [reply synapse/federation/federation_client.py]: See #7089.
