### ISSUE TITLE
AttributeError: 'GenericWorkerSlavedStore' object has no attribute 'get_time_of_last_push_action_before'

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#7054]
Happens when sending out new email notifications. Given it happened on `matrix-org-hotfixes` between Feb 19th and Feb 27th, I assume this was caused by https://github.com/matrix-org/synapse/pull/6964.

**Comment by babolivier** [comment]
Fixed in https://github.com/matrix-org/synapse/pull/7055
