### PR TITLE
import urllib.parse when using urllib.parse.quote

### PR DESCRIPTION
**Pull request by anoadragon453**
We were using `urllib.parse.quote` but only importing `urllib`. Afaik that doesn't work:

```
 ❯ python
Python 3.8.2 (default, Apr  8 2020, 14:31:25) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib
>>> urllib.parse.quote("asd")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'urllib' has no attribute 'parse'
>>> import urllib.parse
>>> urllib.parse.quote("asd")
'asd'
>>> 
```

Broke in https://github.com/matrix-org/synapse/commit/40fb00f5b7a8a9df15169900df218df19423b93e

~~It looks like this would break email registration in Riot, as afaik we use `next_link` there :thinking: However testing, registration on matrix.org via email definitely still works.~~

It's due to the fact that we `import urllib.parse` elsewhere in the codebase. Still, if that ever were to be removed, this would break.

### CODE REVIEW

File: changelog.d/7319.bugfix [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix an incorrect import in IdentityHandler.
```
Comment (richvdh) [inline changelog.d/7319.bugfix:1]: this is probably only a misc, given it worked ok.
