### PR TITLE
Fix 'LruCache' object has no attribute '_on_resize'

### LINKED ISSUE #8586: AttributeError: 'LruCache' object has no attribute '_on_resize'
I'm getting the following after updating `a9a8f2972..85c56445f`

```
2020-10-19 13:52:34,985 - synapse.federation.federation_server - 927 - ERROR - PUT-181 - Failed to handle edu 'm.typing'
Traceback (most recent call last):
  File "/home/erikj/synapse/synapse/federation/federation_server.py", line 923, in on_edu
    await handler(origin, content)
  File "/home/erikj/synapse/synapse/handlers/typing.py", line 328, in _recv_edu
    users = await self.store.get_users_in_room(room_id)
  File "/home/erikj/synapse/synapse/util/caches/descriptors.py", line 153, in __get__
    if expected_thread is not threading.current_thread():
  File "/home/erikj/synapse/synapse/util/caches/deferred_cache.py", line 93, in __init__
  File "/home/erikj/synapse/synapse/util/caches/lrucache.py", line 128, in __init__
  File "/home/erikj/synapse/synapse/util/caches/__init__.py", line 120, in register_cache
    metric_name = "cache_%s_%s" % (cache_type, cache_name)
  File "/home/erikj/synapse/synapse/config/cache.py", line 83, in add_resizable_cache
    properties.resize_all_caches_func()
  File "/home/erikj/synapse/synapse/config/cache.py", line 208, in resize_all_caches
    callback(new_factor)
  File "/home/erikj/synapse/synapse/util/caches/lrucache.py", line 386, in set_cache_factor
AttributeError: 'LruCache' object has no attribute '_on_resize'
```

### PR DESCRIPTION
**Pull request by richvdh**
We need to make sure we are readu for the `set_cache_factor` callback.

Fixes #8586. (Introduced in #8561.)

### CODE REVIEW

**Review by erikjohnston — APPROVED** [review]
It's a little bit gruesome to be passing a not fully instantiated `LruCache` instance around, but I guess that's the least worst option here.

**Comment by richvdh** [comment]
another option might be to separate "constrict metrics object" from "register for resizing", but that sounds like work.
